"""Telegram Bot integration - send audit results to Telegram."""

import os
import json
import requests
from typing import Optional, Union, List
from .core import AuditResult


def format_telegram_report(result: AuditResult) -> str:
    """Format audit result as Telegram message (Markdown)."""
    score = result.score
    grade = result.grade

    if score >= 80:
        emoji = "🟢"
    elif score >= 60:
        emoji = "🟡"
    else:
        emoji = "🔴"

    lines = [
        f"🔍 *SEO Audit Report*",
        f"URL: `{result.url}`",
        f"Score: {emoji} *{score}/100 ({grade})*",
        f"⚡ Load: {result.load_time}s | 📦 Size: {result.details.get('page_size_kb', 'N/A')}KB",
        "",
    ]

    if result.errors:
        lines.append(f"❌ *Errors ({len(result.errors)}):*")
        for e in result.errors[:5]:
            lines.append(f"  • {e.message}")
        if len(result.errors) > 5:
            lines.append(f"  ... +{len(result.errors)-5} more")
        lines.append("")

    if result.warnings:
        lines.append(f"⚠️ *Warnings ({len(result.warnings)}):*")
        for w in result.warnings[:5]:
            lines.append(f"  • {w.message}")
        if len(result.warnings) > 5:
            lines.append(f"  ... +{len(result.warnings)-5} more")
        lines.append("")

    lines.append(f"✅ Passed: {len(result.passed)} checks")

    # CWV summary
    cwv = result.details.get("core_web_vitals", {})
    if cwv:
        cwv_parts = []
        for metric, data in cwv.items():
            status_emoji = {"good": "🟢", "needs_improvement": "🟡", "poor": "🔴"}.get(data.get("status"), "⚪")
            cwv_parts.append(f"{status_emoji}{metric}")
        lines.append(f"📊 CWV: {' | '.join(cwv_parts)}")

    lines.append(f"\n_Generated by SEO-Audit-CLI v2.0_")

    return "\n".join(lines)


def format_batch_telegram_report(results: List[AuditResult]) -> str:
    """Format batch audit results for Telegram."""
    scores = [r.score for r in results]
    avg = round(sum(scores) / len(scores), 1) if scores else 0

    lines = [
        f"🔍 *Batch SEO Audit Report*",
        f"URLs: {len(results)} | Avg Score: *{avg}*",
        "",
    ]

    for r in results[:10]:
        emoji = "🟢" if r.score >= 80 else "🟡" if r.score >= 60 else "🔴"
        lines.append(f"{emoji} *{r.score}* | {r.url[:50]}")

    if len(results) > 10:
        lines.append(f"... +{len(results)-10} more")

    return "\n".join(lines)


def send_to_telegram(
    text: str,
    bot_token: Optional[str] = None,
    chat_id: Optional[str] = None,
    parse_mode: str = "Markdown",
) -> dict:
    """Send message to Telegram via Bot API."""
    token = bot_token or os.environ.get("TELEGRAM_BOT_TOKEN", "")
    cid = chat_id or os.environ.get("TELEGRAM_CHAT_ID", "")

    if not token or not cid:
        raise ValueError("TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID required")

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {
        "chat_id": cid,
        "text": text,
        "parse_mode": parse_mode,
    }

    resp = requests.post(url, json=payload, timeout=10)
    resp.raise_for_status()
    return resp.json()


def send_audit_to_telegram(
    result: Union[AuditResult, List[AuditResult]],
    bot_token: Optional[str] = None,
    chat_id: Optional[str] = None,
) -> dict:
    """Format and send audit result(s) to Telegram."""
    if isinstance(result, list):
        text = format_batch_telegram_report(result)
    else:
        text = format_telegram_report(result)

    return send_to_telegram(text, bot_token=bot_token, chat_id=chat_id)
